### PR TITLE
Refactor - Remove unused import

### PR DESCRIPTION
**Pull request by prasanth08**
Remove unused imports

### CODE REVIEW

**Review by nmahendru — APPROVED** [review]

**Comment by ivmaykov** [comment]
LGTM, but the commit needs to be signed.

@prasanth08 you will need to set up GPG signing and sign the commit before we can merge it.

**Comment by prasanth08** [comment]
I've added the gpg keys.

**Comment by ivmaykov** [comment]
Hi @prasanth08, the commit still says "Unverified" if you click the Commits tab. I think you should `git commit --amend --gpg-sign=...` and then do a forced push to your fork. I also recommend that you rebase your branch onto the latest master so you don't have an unnecessary merge commit.

**Comment by prasanth08** [comment]
I think its best i cut a new branch and make a new pull request.

**Comment by ivmaykov** [comment]
Sure, that's fine too. I'll close this PR and wait for a new one!

**Comment by prasanth08** [comment]
Raised a new one https://github.com/square/subzero/pull/583

**Pull request closed without merging**
